### ISSUE TITLE
Support eslint 8.0.0

### ISSUE THREAD

**Issue by AndysonDK** [borremosch/eslint-plugin-type-graphql#21]
Since upgrading to eslint 8, I'm receiving this error when trying to lint my project:
```
Oops! Something went wrong! :(

ESLint: 8.2.0

TypeError: Failed to load plugin 'type-graphql' declared in '.eslintrc.js#overrides[0]#overrides[1]#overrides[0]': Class extends value undefined is not a constructor or null
Referenced from: /home/anders/Projects/syncbase/.eslintrc.js
    at Object.<anonymous> (/home/anders/Projects/syncbase/node_modules/eslint-plugin-type-graphql/node_modules/@typescript-eslint/experimental-utils/dist/ts-eslint/CLIEngine.js:12:34)
    at Module._compile (/home/anders/Projects/syncbase/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (/home/anders/Projects/syncbase/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/anders/Projects/syncbase/node_modules/eslint-plugin-type-graphql/node_modules/@typescript-eslint/experimental-utils/dist/ts-eslint/index.js:14:14)
    at Module._compile (/home/anders/Projects/syncbase/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)

```
Can you update this plugin to support eslint `^8.0.0`, that would be great!

**Comment by mta-trackunit** [comment]
I added a PR for it
https://github.com/borremosch/eslint-plugin-type-graphql/pull/22
